### PR TITLE
feat(hmr): support popular css transpilers

### PR DESCRIPTION
**Pull request by jods4**
Mirrors aurelia/templating-resources#279

### CODE REVIEW

**Comment by niieani** [comment]
Thanks! I was too busy to do this myself.

**Comment by AdamWillden** [comment]
@niieani, @jods4 is there any reason this has not made it into a release? I know there's much debate about the viability of HMR in Aurelia (prior to 2.0) and it's not the focus right now but I could very much benefit from this commit being released.

**Comment by AdamWillden** [comment]
@EisenbergEffect can you shed any light on this please?

**Comment by EisenbergEffect** [comment]
Doh! I just did a release pass and somehow totally missed this! I apologize. I'll look into it this evening.

**Pull request merged**
